# Generated by Django 3.2.22 on 2024-02-27 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_account_account_type 2'),
        ('account', '0011_alter_account_account_type'),
        ('account', '0011_alter_account_account_type 2'),
    ]

    operations = [
    ]
