# Generated by Django 5.0.1 on 2024-03-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_account_user_id_alter_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Teacher')], default='S', max_length=1),
        ),
    ]
