# Generated by Django 4.2.6 on 2024-01-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0002_lesson_lesson_num_unit_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="number",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="unit",
            name="number",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="progress",
            name="tree_type",
            field=models.CharField(
                choices=[("B", "B"), ("A", "A")], default="A", max_length=1
            ),
        ),
    ]
