# Generated by Django 5.0 on 2024-01-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_quiz_quiz_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.AddField(
            model_name='unit',
            name='tree_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
