# Generated by Django 4.2.6 on 2024-01-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0003_lesson_number_unit_number_alter_progress_tree_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="number",
        ),
        migrations.AlterField(
            model_name="quiz",
            name="quiz_type",
            field=models.CharField(
                choices=[("MCQ", "Multiple Choice"), ("FRQ", "Free Response")],
                default="MCQ",
                max_length=3,
            ),
        ),
    ]
