# Generated by Django 5.0.1 on 2024-02-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_delete_name_unit_tree_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('topic_num', models.IntegerField(default=0)),
                ('units_total', models.IntegerField(default=0)),
                ('tree_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_type',
        ),
    ]
