# Generated by Django 5.0.1 on 2024-02-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_remove_quiz_name_alter_progress_tree_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='tree_type',
            field=models.CharField(choices=[('B', 'B'), ('A', 'A')], default='A', max_length=1),
        ),
    ]
