# Generated by Django 5.0.1 on 2024-02-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_alter_progress_tree_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
