# Generated by Django 3.2.22 on 2024-02-27 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_topic_remove_quiz_quiz_type 2'),
        ('classroom', '0006_remove_quiz_name_alter_progress_tree_type 2'),
        ('classroom', '0007_alter_progress_tree_type'),
        ('classroom', '0007_alter_progress_tree_type 2'),
    ]

    operations = [
    ]
