# Generated by Django 5.0.1 on 2024-03-15 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_lesson_done'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='link',
            new_name='video_link',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='name',
            new_name='topic_name',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='number',
            new_name='number_of_lessons',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='image',
            new_name='unit_icon',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='members',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='name',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='done',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_num',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_num',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='tree_name',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='units_total',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='lessons_total',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='name',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='tree_name',
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.unit'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_script',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='lesson_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.lesson'),
        ),
        migrations.AddField(
            model_name='topic',
            name='tree_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='unit',
            name='topic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.topic'),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Lesson_Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', models.BooleanField(default=False)),
                ('date_assigned', models.DateTimeField()),
                ('lesson_grade', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('recent_date_attempted', models.DateTimeField()),
                ('lesson_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.lesson')),
                ('user_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons_Completed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_completed', models.IntegerField(default=0)),
                ('lessons_total', models.IntegerField(default=0)),
                ('lesson_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.lesson')),
                ('user_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic_Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_name', models.CharField(blank=True, max_length=20, null=True)),
                ('topic_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.topic')),
                ('user_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_To_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
                ('user_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
