# Generated by Django 5.0.1 on 2024-03-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_rename_link_lesson_video_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_link',
            field=models.TextField(),
        ),
    ]
