# Generated by Django 5.0.1 on 2024-03-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_alter_lesson_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_number',
            field=models.IntegerField(null=True),
        ),
    ]
