# Generated by Django 5.0.1 on 2024-03-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_topic_topic_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_number',
            field=models.IntegerField(null=True),
        ),
    ]
