# Generated by Django 5.0.1 on 2024-03-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_unit_unit_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_num',
            field=models.IntegerField(null=True),
        ),
    ]
