# Generated by Django 5.0.1 on 2024-03-28 02:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_lesson_lesson_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson_assignment',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='lesson_assignment',
            name='date_assigned',
        ),
        migrations.RemoveField(
            model_name='lesson_assignment',
            name='lesson_grade',
        ),
        migrations.RemoveField(
            model_name='lesson_assignment',
            name='recent_date_attempted',
        ),
        migrations.RemoveField(
            model_name='lessons_completed',
            name='lessons_completed',
        ),
        migrations.RemoveField(
            model_name='lessons_completed',
            name='lessons_total',
        ),
        migrations.AddField(
            model_name='lesson_assignment',
            name='attempts_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson_assignment',
            name='date_available',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lesson_assignment',
            name='date_due',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lessons_completed',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessons_completed',
            name='date_attempted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lessons_completed',
            name='lesson_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessons_completed',
            name='lesson_grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic_tree',
            name='progress_plant1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='topic_tree',
            name='progress_plant2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='topic_tree',
            name='progress_plant3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='topic_tree',
            name='progress_plant4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='topic_tree',
            name='progress_plant5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
