# Generated by Django 5.0.1 on 2024-03-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_remove_lesson_assignment_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic_tree',
            name='progress_plant1',
        ),
        migrations.RemoveField(
            model_name='topic_tree',
            name='progress_plant2',
        ),
        migrations.RemoveField(
            model_name='topic_tree',
            name='progress_plant3',
        ),
        migrations.RemoveField(
            model_name='topic_tree',
            name='progress_plant4',
        ),
        migrations.RemoveField(
            model_name='topic_tree',
            name='progress_plant5',
        ),
        migrations.AddField(
            model_name='topic',
            name='progress_plant1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='topic',
            name='progress_plant2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='topic',
            name='progress_plant3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='topic',
            name='progress_plant4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='topic',
            name='progress_plant5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
