export const ACCOUNT_LOGIN_REQUEST = 'ACCOUNT_LOGIN_REQUEST';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGIN_FAILURE = 'ACCOUNT_LOGIN_FAILURE';

export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';

export const ACCOUNT_REGISTER_REQUEST = 'ACCOUNT_REGISTER_REQUEST';
export const ACCOUNT_REGISTER_SUCCESS = 'ACCOUNT_REGISTER_SUCCESS';
export const ACCOUNT_REGISTER_FAILURE = 'ACCOUNT_REGISTER_FAILURE';
